ROOT_FOLDER = "Pico_VNA_Project"
# ROOT_FOLDER = "picosdk-picovna-python-examples"

# Folder names
CALIBRATION_FOLDER = "calibrations"
EXPERIMENT_PLANS_FOLDER = "experiment_plans"

SETTINGS_FOLDER = "settings"
# Joined to SETTINGS_FOLDER
GRAPH_STYLE_FOLDER = "graph_style"

PICKLE_FOLDER = "pickles"
# Joined to PICKLE_FOLDER
CLASSIFIER_FOLDER = "classifiers"
COMBINED_DF_FOLDER = "full_dfs"
FULL_RESULTS_DF_FOLDER = "full_results_dfs"


RESULTS_FOLDER = "results"
# Joined to RESULTS_FOLDER
DATA_FOLDER = "data"
GRAPH_FOLDER = "graphs"
CSV_FOLDER = "csvs"
TOUCHSTONES_FOLDER = "touchstones"

CONFIRM_TEMP_FILE = False
TRAIN_TEST_SEED_VALUE = 42

# Classification Defaults
DEFAULT_CLASSIFICATION_TRAIN_TEST_SPLIT = 0.4
DEFAULT_RANDOM_STATE_DEFAULT = 42
DEFAULT_BATCH_PROCESSING_SIZE = 500
DEFAULT_TRAINING_SAMPLE_SIZE = 100

# Graph settings
DEFAULT_COLOUR_MAP = "winter"
DEFAULT_FIGURE_SIZE = (14, 9)
DEFAULT_FILE_TYPE = "svg"
